git:
  depth: 1

os:
  - linux
  - osx
  - windows

language: node_js

node_js:
  - 14

jdk:
  - openjdk11

install:
  - npm install

script:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - chmod +x $TRAVIS_BUILD_DIR/install-jdk.sh
  - export JAVA_HOME=$HOME/openjdk11
  - $TRAVIS_BUILD_DIR/install-jdk.sh -F 11 --target $JAVA_HOME

jobs:
  include:
    - os: linux
      script:
        - echo "linux"
        - java -version
        - jest --testNamePattern linux
    - os: osx
      osx_image: xcode13.0
      script:
        - echo "mac"
        - java -version
        - xcodebuild -version
        - jest --testNamePattern mac
    - os: windows
      script:
        - echo "windows"
        - java -version
        - jest --testNamePattern win
