git:
  depth: 1

os:
  - linux
  - osx
  - windows

language: node_js

node_js:
  - 14

jdk:
  - openjdk11

install:
  - npm install

jobs:
  include:
    - os: linux
      script:
        - echo "linux"
        - jest --testNamePattern linux
    - os: osx
      osx_image: xcode13.0
      script:
        - echo "mac"
        - jest --testNamePattern mac
    - os: windows
      script:
        - echo "windows"
        - jest --testNamePattern win
