git:
  depth: 1

os:
#  - linux
#  - osx
  - windows

language: node_js

node_js:
  - 14

jdk:
  - openjdk11

install:
  - npm install

script:
  - echo "Test"

jobs:
  include:
#    - os: linux
#      script:
#        - echo "linux"
#        - java -version
#        - jest --testNamePattern linux
#    - os: osx
#      osx_image: xcode12.5
#      script:
#        - echo "mac"
#        - java -version
#        - xcodebuild -version
#        - jest --testNamePattern mac
    - os: windows
      script:
        - echo "windows"
        - choco install jdk8
        - export PATH=$PATH:"/c/Program Files/Java/jdk1.8.0_191/bin"
        - java -version
        - jest --testNamePattern win
